# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perdidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=50, null=True)),
                ('lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('coordenada', models.CharField(blank=True, max_length=50, null=True)),
                ('dni', models.CharField(blank=True, max_length=10, null=True)),
                ('imagen', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'perdidos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pista',
            fields=[
                ('idpista', models.AutoField(primary_key=True, serialize=False)),
                ('idusuario', models.CharField(blank=True, max_length=300, null=True)),
                ('idperdido', models.CharField(blank=True, max_length=300, null=True)),
                ('asunto', models.CharField(blank=True, max_length=500, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'pista',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('usuario', models.CharField(blank=True, max_length=60, null=True)),
                ('clave', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
