# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-24 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170617_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('dni', models.CharField(blank=True, max_length=10, null=True)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('detalle', models.CharField(blank=True, max_length=600, null=True)),
                ('idusuario', models.CharField(blank=True, max_length=200, null=True)),
                ('idperdido', models.CharField(blank=True, max_length=200, null=True)),
                ('iddenuncia', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
                'db_table': 'denuncia',
            },
        ),
    ]
